apiVersion: v1
kind: Secret
metadata:
  name: appsecret
type: Opaque
StringData:
  username: admin
  password: password
  DATABASE_URL: "postgresql://postgres:1234@database-service:5432/stg1" # K8s Service Name use kiya
  # Note: Postgres image ko chalne ke liye ye specific env variables chahiye hote hain:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: stg1
  